// src/app/layout.js
import "./globals.css";
import { Geist, Geist_Mono, DM_Sans } from "next/font/google";
import { WalletContextProvider } from "@/components/walletContextProvider";
import { WalletDashboard } from "@/components/WalletDashboard"; // ✅ client wrapper

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const dmSans = DM_Sans({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      className={`${geistSans.variable} ${geistMono.variable} ${dmSans.variable}`}
      lang="en"
    >
      <body>
        <WalletContextProvider>
          {children}
          <WalletDashboard /> {/* client-only */}
        </WalletContextProvider>
      </body>
    </html>
  );
}
